import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import { groq } from "next-sanity";
import { sanityClient, urlFor } from "../lib/sanity";

const recipesQuery = groq`*[_type == "recipe"]{
  _id,
  name,
  slug,
  mainImage
}`;

const Home = ({ recipes }: any) => {
  return (
    <div>
      <Head>
        <title>Dyrean&apos;s Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to Dyrean&apos;s Kitchen</h1>
      <ul className="recipes-list">
        {recipes?.length > 0 &&
          recipes.map((recipe: any) => (
            <li key={recipe._id} className="recipe-card">
              <Link href={`recipes/${recipe.slug.current}`}>
                <a>
                  <div className="recipe-image">
                    <Image
                      height="300"
                      width="300"
                      layout="responsive"
                      placeholder="blur"
                      objectFit="cover"
                      blurDataURL={urlFor(recipe.mainImage).width(300).url()}
                      src={urlFor(recipe.mainImage).url()}
                      alt={recipe.name}
                    />
                  </div>
                  <span>{recipe.name}</span>
                </a>
              </Link>
            </li>
          ))}
      </ul>
    </div>
  );
};

export default Home;

export const getStaticProps = async () => {
  const recipes = await sanityClient.fetch(recipesQuery);
  const props = {
    recipes,
  };
  return {
    props,
  };
};
